#!/bin/bash

. jenv

if [ $RESULT -eq 1 ]
then
    echo "Exiting..."
    exit 1
fi


start_interactive_terminal() {
    echo -n ">> "
    read DATA
    while [ "$DATA" != "exit()" ]
    do
        parse_data "$DATA"
        echo -n ">> "
        read DATA
    done
    echo ">>"
}

parse_data() {
    args=()
    COUNTER=0
    for arg in $1
    do
        args[$COUNTER]=$arg
        COUNTER=$[ $COUNTER + 1 ]
    done

    case ${args[0]} in
        block)            
            get_block_of_code
            compile_java_file
            execute_java_file "$CLASS_FILE" "$CLASS_NAME"
            ;;
        class_def)
            if [ "${args[1]}" == "" ]
            then
                echo "Usage: class_def class_name"
            else
                create_class ${args[1]}
            fi
            ;;
        cls)
            clear
            ;;
        *)    
            _DATA=$1
            echo $_DATA | sed "s/\"/\\\"/g" > sed_out
            create_java_file "`cat sed_out`" "$JAVA_FILE" "$CLASS_FILE" "$CLASS_NAME"
            compile_java_file 
            execute_java_file "$CLASS_FILE" "$CLASS_NAME"
            ;; 
    esac
}

create_class() {
    cd ~/.jarminal
    touch "$1.java"
    
    JAVA_FILE="$1.java"
    CLASS_FILE="$1.class"
    CLASS_NAME="$1"
        
    read_append "endclass_def" $JAVA_FILE

    compile_java_file 
}

get_block_of_code() {
    cd ~/.jarminal

    COUNT=0

    while [ -f "JarminalBlock$COUNT.java" ]
    do
        COUNT=$[ $COUNT + 1 ]
    done

    JAVA_FILE="JarminalBlock$COUNT.java"
    CLASS_FILE="JarminalBlock$COUNT.class"
    CLASS_NAME="JarminalBlock$COUNT"

    create_partial_java_file "$JAVA_FILE" "$CLASS_FILE" "$CLASS_NAME"

    read_append "endblock" $JAVA_FILE

    complete_java_file
}

compile_java_file() {
    cd ~/.jarminal
    `javac $CMD_OPTIONS $JAVA_FILE`
}

complete_java_file() {
    cd ~/.jarminal
    echo " System.exit(0); } }" >> $JAVA_FILE
}


case "$1" in
    -e)
        create_java_file "$2" "$JAVA_FILE" "$CLASS_FILE" "$CLASS_NAME"
        compile_java_file 
        execute_java_file "$CLASS_FILE" "$CLASS_NAME"
        ;;
    -i)
        start_interactive_terminal
        ;;
    *)
        echo "Type jarminal --help for help info"
esac        

cd ~/.jarminal
rm *
exit 0;

